In [1]:
#Experiment_no : 5

In [2]:
#Aim: Creation of arrays

In [3]:
#Name: Shruti Giri
#Roll no: 17
#Sec: C
#Subject: ET 1

In [16]:
import numpy as np

In [17]:
#creating 1D array
a1=np.array([10,20,30,40])

In [18]:
a1

array([10, 20, 30, 40])

In [19]:
#creating 2D array
a2=np.array([[20,44,32,64],[22,14,71,26]])

In [20]:
a2

array([[20, 44, 32, 64],
       [22, 14, 71, 26]])

In [21]:
#creating 2D array using matrix
a3=np.matrix('11,,36;45,21;64,49')

In [22]:
a3

matrix([[11, 36],
        [45, 21],
        [64, 49]])

In [25]:
#creating an array of 20 random integers
arr = np.random.randint(1,101,size=20)
print(arr)

[20 75 11 92 53 98 94  9 38 94 47 67 48 88 77 85 35 25 96 13]
